"""Add piece_id to content_puzzle_cell

Revision ID: 7a4d4a62aab6
Revises: ff3ea48c021b
Create Date: 2025-07-17 02:10:39.939714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4d4a62aab6'
down_revision: Union[str, Sequence[str], None] = 'ff3ea48c021b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_puzzle_cell', sa.Column('piece_id', sa.String(length=1), nullable=False))
    op.create_foreign_key(None, 'content_puzzle_cell', 'master_piece', ['piece_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_puzzle_cell', type_='foreignkey')
    op.drop_column('content_puzzle_cell', 'piece_id')
    # ### end Alembic commands ###
