"""Update master_base_puzzle_cell for piece_id

Revision ID: f02efb69dbe2
Revises: 7a4d4a62aab6
Create Date: 2025-07-17 03:45:11.832492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02efb69dbe2'
down_revision: Union[str, Sequence[str], None] = '7a4d4a62aab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
