"""initial schema

Revision ID: fced06f04950
Revises: 
Create Date: 2025-07-15 04:17:08.529321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fced06f04950'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_difficulty',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('master_piece',
    sa.Column('id', sa.String(length=1), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('shape_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_puzzle_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('master_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('master_base_puzzle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('puzzle_type_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['master_user.id'], ),
    sa.ForeignKeyConstraint(['puzzle_type_id'], ['master_puzzle_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_puzzle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_puzzle_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty_id', sa.UUID(), nullable=False),
    sa.Column('puzzle_type_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['master_user.id'], ),
    sa.ForeignKeyConstraint(['base_puzzle_id'], ['master_base_puzzle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['difficulty_id'], ['master_difficulty.id'], ),
    sa.ForeignKeyConstraint(['puzzle_type_id'], ['master_puzzle_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_base_puzzle_cell',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_puzzle_id', sa.UUID(), nullable=False),
    sa.Column('x', sa.SmallInteger(), nullable=False),
    sa.Column('y', sa.SmallInteger(), nullable=False),
    sa.Column('z', sa.SmallInteger(), nullable=False),
    sa.Column('value', sa.CHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['base_puzzle_id'], ['master_base_puzzle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value'], ['master_piece.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_puzzle_id', 'x', 'y', 'z', name='uq_base_puzzle_cell')
    )
    op.create_table('content_puzzle_cell',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('puzzle_id', sa.UUID(), nullable=False),
    sa.Column('x', sa.SmallInteger(), nullable=False),
    sa.Column('y', sa.SmallInteger(), nullable=False),
    sa.Column('z', sa.SmallInteger(), nullable=False),
    sa.Column('value', sa.CHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['content_puzzle.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value'], ['master_piece.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puzzle_id', 'x', 'y', 'z', name='uq_content_puzzle_cell')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_puzzle_cell')
    op.drop_table('master_base_puzzle_cell')
    op.drop_table('content_puzzle')
    op.drop_table('master_base_puzzle')
    op.drop_table('master_user')
    op.drop_table('master_puzzle_type')
    op.drop_table('master_piece')
    op.drop_table('master_difficulty')
    # ### end Alembic commands ###
