#!/usr/bin/env python3
"""
[Instagram Carousel] Post a SoChi BLOCKS puzzle as Instagram Carousel.

SNS Strategy:
  Instagram Carousel → Puzzle catalog (パズル図鑑)
  - Instagram profile grid = puzzle encyclopedia
  - Cover image = layer.png  ← REQUIRED (puzzle catalog cover / カタログ表紙)
  - Consistent layer.png covers create a unified catalog look on the profile grid

Cover image rule:
  layer.png is the puzzle layer diagram generated by generate_instagram_images.py.
  It serves as the catalog cover for each puzzle post.
  Without layer.png, the carousel cannot be posted — it is mandatory.

Usage:
  python scripts/publish_instagram_carousel.py \\
    --dir docs/images/20260312/004/ \\
    --base-url https://souchi-lab.github.io/sochi-blocks
"""

import argparse
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

sys.path.insert(0, str(Path(__file__).resolve().parent))
from publish_instagram import post_to_instagram

_LOG = "[Instagram Carousel]"


def main():
    parser = argparse.ArgumentParser(
        description="[Instagram Carousel] Post a SoChi BLOCKS puzzle catalog post",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
SNS Strategy: Instagram Carousel → Puzzle catalog
  layer.png is mandatory — it is the puzzle catalog cover image.
  Instagram profile grid shows layer.png as a visual encyclopedia of puzzles.
""",
    )
    parser.add_argument("--dir", required=True, help="Path to asset directory")
    parser.add_argument("--base-url", required=True, help="Public base URL for assets")
    args = parser.parse_args()

    asset_dir = Path(args.dir)
    if not asset_dir.is_dir():
        print(f"{_LOG} ERROR: {asset_dir} is not a directory.")
        sys.exit(1)

    # Validate layer.png — REQUIRED for carousel catalog cover
    layer_png = asset_dir / "layer.png"
    if not layer_png.exists():
        print(f"{_LOG} ERROR: Instagram carousel requires layer.png")
        print(f"  This image is used as puzzle catalog cover.")
        print(f"  Expected: {layer_png}")
        print(f"  Generate it with: python scripts/generate_instagram_images.py --puzzle_id <id>")
        sys.exit(1)

    # Validate caption
    caption_path = asset_dir / "caption_instagram.txt"
    if not caption_path.exists():
        caption_path = asset_dir / "caption.txt"
    if not caption_path.exists():
        print(f"{_LOG} ERROR: No caption file found in {asset_dir}")
        print(f"  Expected: caption_instagram.txt or caption.txt")
        sys.exit(1)

    print(f"{_LOG} Posting carousel for {asset_dir.name}")
    print(f"  Cover:   {layer_png.name}  (puzzle catalog cover)")
    print(f"  Caption: {caption_path.name}")

    ok = post_to_instagram(asset_dir, args.base_url)

    if ok:
        print(f"{_LOG} Successfully posted!")
    else:
        print(f"{_LOG} Post failed.")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
